version'3'

services:
  zookeeper:
    container_name:
      zookeeper_merge
    image:
      wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      -kafka_merge_net
    kafka:
      container_name:
        kafka_merge
      image:
        wurstmeister/kafka
      depends_on:
        - zookeeper
      ports:
        "8011:8011"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ADVERTISED_PORT: 8011
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        ZK_SERVER: zookeeper:2181
        ADVERTISED_HOST: localhost
        CONSUMER_THREADS: 5
        BROKER_ID: 1
        ADVERTISED_PORT: 8011

      volumes:
        - /var/rin/docker.sock:/var/run/docker.sock
      networks:
        - kafka_merge_net
networks:
  kafka_merge_net:
    driver: bridge