#server:
#  port: 8011
#spring:
#  data:
#    mongodb:
#      database: db_products
#      port: 27017
#      host: localhost
#      username: root
#logging:
#  config:
#    classpath: logback-test.xml

#config-server conection
spring:
  application:
    name: bootcoin-service
  config:
    import: configserver:http://localhost:8081
